### ISSUE TITLE
Is it possible to connect multiple sensors to esp8266

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#1]
Juan, thanks for providing the examples and the info in the wiki...I have just a general noob question, is it possible to connect multiple sensors to the esp8266? For example temperature+humidity, light, PIR, etc.
How much of them is possible? :)

Thanks!

**Comment by juanpintom** [comment]
Yes for sure just use different pin for each sensor,  am working on a Pcb
that have all the sensors integrated and I'll share the sketch when it's
done,  It's already working on a prototype.
Regards

**Comment by marksev1** [comment]
Niiiceee, do you want me to close the issue or let it open for reference to your new "multisensor" project. Btw which sensors are you going to use?

**Comment by juanpintom** [comment]
Keep it open and when I share the sketch and the PCB I put here and close
it.

 I designed a simple one side pcb of about 5x5cm that have integrated:
- 12v to 3.3v
- 3 Led Strip (or 1 RGB) control
- DHT connector
- Dallas connector
- I2C connector
- Lux measure with ADC pin and LDR

And in other "bigger" version (5x7cm) with all I said before and
an Attiny with the circuit to connect directly a CT sensor.

Regards

2015-06-03 12:48 GMT+02:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Pretty cool, what about this PIR sensor HC-SR501 http://www.ebay.com/itm/New-quality-HC-SR501-Infrared-PIR-Motion-Sensor-Module-for-Arduino-Raspberry-pi-/111360866212?pt=LH_DefaultDomain_0&hash=item19ed9ff7a4

That one could be connected to the ADC pin right?

Why do you have two spots for two different temperature sensors (dht and dallas)? Just for redundancy so one can use one or another?

**Comment by juanpintom** [comment]
I'm thinking about, but these PIR sensor works at 5v and I'll use a Lm317
to get 3.3v from a 12vin, one option can be add another Lm317 to get 5v, I
think about.

On the pcb is optional put a dht a Dallas or both,  and the unused pin can
be used to other function,  like a push-button, an ir receiver (am working
on it),  or other many options Souliss offers,  suggestions are welcome.

Regards

**Comment by marksev1** [comment]
Would it be possible to feed the entire circuitry also with 5V, and then regulate it to 3.3V for those sensors and stuff that needs 3.3V? or a separate power rail for 5V (for the pir sensor)? Do you have 12V laid around the house? 
I'm thinking about 5V since then I could use a regular phone charger connected to a http://www.ebay.com/itm/MB102-Breadboard-Power-Supply-Module-3-3V-5V-F-Solderless-Arduino-mini-usb-/131224325489?pt=LH_DefaultDomain_0&hash=item1e8d944d71

So I could have a standardized and easy way to connect the different modules to the power outlets.

Regards,

**Comment by juanpintom** [comment]
Yes, it's possible to power with 5v sure. I use 12v AC/DC converter to
power with the same converter the Led Strips and the module, I haven't a
laid around the House, but Im planning it.

Anyway I'll add a 5v regulator to the scheme to connect a PIR or other 5v
devices, but the DHT, Dallas and others can be powered with 3.3v.

Regards

2015-06-04 18:12 GMT+02:00 marksev1 notifications@github.com:

**Comment by juanpintom** [comment]
Sorry by the delay on this, here is an early example using multiple sensors, I still working on the first prototypes of the PCB (I have two running for two weeks with no problems)
http://pastebin.com/b1GBc2FK

Regards

**Comment by marksev1** [comment]
Juan thanks for all your work on this project, as you know I'm following it on Souliss groups. Its amazing how good Souliss is progressing every day :).

Would such a magnetic door/window sensor also be an option for addition into the sketch -> http://www.ebay.com/itm/10-pcs-MC-38-Wired-Door-Window-Sensor-Magnetic-Switch-Home-Alarm-System-Detector-/350944895445?hash=item51b5f221d5

For checking if doors/windows are closed. I've seen on the google groups that someone started to do door closed/opened detection based on mpu6050, but did not finish.  I think this solution with magnetic switches would be easier.

I have also full of other ideas but thats it for now hehe :D

**Comment by juanpintom** [comment]
Yes, you can use any sensor, just connect to a PIN and must work :) If you
need help open a post on ML :P

This post may help us, but seems easy to integrate:
http://iot-playground.com/2-uncategorised/36-esp8266-door-window-sensor-nodemcu-lua-no-arduino

Regards

2015-08-22 23:50 GMT+02:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Would be cool if Easyiot server would support Souliss also, like Openhab does. This Easyiot just supports Mysensors. 

Also here there is some arduino code: http://iot-playground.com/10-low-power-door-window-sensor

**Comment by juanpintom** [comment]
I not refer to easyiot, just to the wiring of the MC sensor, you can
connect this to the ESP on this way and handle everthing from Souliss.

Regards.

2015-08-24 16:59 GMT+02:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Juan, is the pcb and parts list ready so i can start ordering stuff?

**Comment by juanpintom** [comment]
The board its working, I made various prototypes working on my house, Im
working on the next version of the PCB because the LM317 configured at 3.3v
its overheating, it works but I want to make a v2 before send to production.

Regards

2015-09-03 13:23 GMT+02:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
I might be ok with already this version since I think I'll feed it with 5v. Are you going to add another vreg to the design, so from 12 > 5 > 3.3v. Because maybe if I use ws2812 leds I can stay with 5v on all my intended "nodes". I plan to use about 5 of them for a start. Lm317 in your setup is overheating since its converting from 12 to 3.3v right? :)

**Comment by juanpintom** [comment]
Yes, it is, power is disipated as heat when voltage comes from 12v to 3.3v,

I suggest you power with a 5v regulated power source or up the voltage to
7-9v and LM317.

Regards

2015-09-03 17:22 GMT+02:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Ok so then I might be good to start right? Can you send me maybe then the gerbers+schematic+parts list on my mail. In which software did you draw it (Eagle, Diptrace or Kicad maybe?)?

**Comment by juanpintom** [comment]
I shared a folder with the gerber and fritzing file, I designed this pcb
for me, and finally I shared with the community but there is no scheme or
part list, you can see the parts on Fritzing, Im working on the next
version now and this is why this "old" designs wasn't updated BUT is
totally functional ;) . I will work with eagle on the next version and
scheme BOM and silk will be done to send to production.  I explained on
this post:
https://groups.google.com/d/msg/souliss/H0g56a0Q4oM/2LEm-4mDo_8J

Regards

2015-09-03 18:03 GMT+02:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Cool thanks Juan, now I get it hehe!
