### ISSUE TITLE
[ADD] Window/Door magnetic contact sensor

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#29]
Hi Juan, 

please also add support for Window/Door magnetic contact sensor for alarm purposes. If its already on the list then close the issue :).

Cheers,

**Comment by juanpintom** [comment]
This was added before, you can connect an endstop or magnetic field on pins
4 and 5. It have LowDigIn command so the sensor must be UP (3.3v) when it's
closed and 0 when it's open ( alarm enabled )

You must enable this on the third combobox on configuration.

Regards

2016-01-03 22:40 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
This sensor right http://p.globalsources.com/IMAGES/PDT/B1071244129/Wired-Magnet-Door-Magnetic-Contact-Sensor.jpg?   Should I close issue since its already implemented?

**Comment by juanpintom** [comment]
Yes, you can wire with this sensors, I don't tested but must work well.
Maybe I'll add inverted logic to the alarm, but this sensors are NC.

Regards

2016-01-06 12:40 GMT+01:00 marksev1 notifications@github.com:
