### ISSUE TITLE
What are you doing with GPIO15 and what are you doing?

### ISSUE THREAD

**Issue by tytower** [juanpintom/Souliss_ESP_Examples#3]
In the code 
// ***\* Define here the right pin for your ESP module ****
# define OUTPUTPIN 15

So this is supposed to be held low at boot or it does not boot . So how are you getting around this ass your code is setting the pin as an output . Am I correct in that ?

I notice you have not answered the previous issue either .
Have you actually had your code running on an ESP8266?

**Comment by Testato** [comment]
The core itself set this pin as an Input at the Boot.
So you need a pulldown or a manual switch for give to it a low value.
After the boot process you can use it like an output pin.

**Comment by juanpintom** [comment]
Hi!, I actually use ESP12 or ESP12E with an Adapter. GPIO15 is connected to a TIP122 to control a led strip.
If you see the adapter it connects GPIO15 to GND with a Pulldown resistor.
http://img.dxcdn.com/productimages/sku_379296_1.jpg
This is why works with no problems.

Anyway you can use any other pin :P

Regards
