### ISSUE TITLE
[ADD] RFID reader support - RC522

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#31]
Would be cool for maybe disarming alarm or setting house party mode or turning on robot vacuum cleaner or something like that :). Or maybe just coolness factor :D.

What do you think?

**Comment by juanpintom** [comment]
This can be easily integrated on any ESP Device, you can see examples like
this:
https://github.com/Jorgen-VikingGod/ESP8266-MFRC522/blob/master/ESP8266-MFRC522.ino

Maybe I'll integrate on Souliss, but I have'nt free pins on my board to
connect it to. This will be done when I've some time, but will not be
merged with my "easy-configurable" code.

2016-01-06 12:44 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Yeah a separate Souliss integration would be nice. Cool :)
