### ISSUE TITLE
Add support for Baro in Telnet branch

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#33]
Hi Juan,

can you maybe please add support for baro in Telnet branch so I can test it (bmp085/bmp180).

Thanks!

**Comment by juanpintom** [comment]
Was added a long time ago.

Regards

2016-02-14 11:13 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Really, since this week I tried telnet branch, I couldn't choose all of it. Can I have ds-temp + baro + pir?

Also regarding i2c lcd I have already one prepared for testing :D
