### ISSUE TITLE
Please add schematic for LDR voltage divider

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#34]
Hi Juan, since I'm a noob I would appreciate the schematic for the LDR esp voltage divider so I don't burn the esp. Thanks!

**Comment by juanpintom** [comment]
Its just a voltage divider from 5v to 1v, look at google for a schematic I
havent with me now and am at work :P

Regards

2016-02-14 17:06 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Good work Juan :D

**Comment by juanpintom** [comment]
:P

2016-02-15 15:57 GMT+01:00 marksev1 notifications@github.com:

**Comment by marksev1** [comment]
Oh so it a voltage divider from 5v to 1v, really, I thought it was from 3.3v to 1v? I'm gonna draw a sketch and then ask you if its correct :D :P. A noob must always be careful :D

**Comment by darknixt** [comment]
Juan disculpa mi intromisión, te quiero realizar una pregunta de una raspberry 2 sobre un tema de hyperion, creo que podrías ayudarme, te lo agradecería, te dejo aquí mi correo y si puedes y lo crees conveniente escríbeme.

Gracias.

darknixt@gmail.com

**Comment by juanpintom** [comment]
I'll try to post a scheme and R values this night :P

Regards

**Comment by marksev1** [comment]
Thanks!
