### ISSUE TITLE
MQTT support, questions

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#35]
Juan so I see that you have planned MQTT support. 

Will it be just tied in with Adafruit.io, or will there also be a possibility to read the mqtt sentences with a local "Mosquitto MQTT" broker on a RPI, for example.

Thanks for answering.

**Comment by juanpintom** [comment]
Its planned but I don't know when as I said at ML.

**Comment by marksev1** [comment]
I'm not asking when, I'd like to know if it would work also with offline broker - Moquitto http://mosquitto.org/

**Comment by marksev1** [comment]
Aparently this https://github.com/Imroy/pubsubclient is the library to use.
