### ISSUE TITLE
I have a suggestion for a more robust Webconfig

### ISSUE THREAD

**Issue by marksev1** [juanpintom/Souliss_ESP_Examples#36]
Hello Juan,

just now I tried the webconfig from EasyESP project and its way more robust and straight-forward then yours. It worked better. Firstly, the AccesPoint had way better signal, secondly I didn't have to  turn off my wireless router for the settings to get saved, thirdly it gave acknowledgements that settings were saved. It was overall a way better and more pleasant experience.

Here are some links: https://github.com/ESP8266nu/ESPEasy
http://www.esp8266.nu/index.php/EasySetup

**Comment by juanpintom** [comment]
I saw this interface before but I maded a lot of work with my interface to
change not to other :S  If anybody wants to collaborate make a new branch.

Regards.

2016-02-16 13:20 GMT+01:00 marksev1 notifications@github.com:
